exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(EDDBC9ff) rgba(523D29ff) 45deg
    col.inactive_border = rgba(573D2Fff) rgba(B58968ff) 45deg
}

group {
    col.border_active = rgba(EDDBC9ff) rgba(523D29ff) 45deg
    col.border_inactive = rgba(573D2Fcc) rgba(B58968cc) 45deg
    col.border_locked_active = rgba(080909ff) rgba(050606ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(111213cc) 45deg
}
