exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(D638CCff) rgba(52294Fff) 45deg
    col.inactive_border = rgba(211735ff) rgba(4A3C74ff) 45deg
}

group {
    col.border_active = rgba(D638CCff) rgba(52294Fff) 45deg
    col.border_inactive = rgba(211735cc) rgba(4A3C74cc) 45deg
    col.border_locked_active = rgba(0E0D0Dff) rgba(E0E4E0ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
