exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(EDC3A2ff) rgba(523B29ff) 45deg
    col.inactive_border = rgba(442920ff) rgba(C68773ff) 45deg
}

group {
    col.border_active = rgba(EDC3A2ff) rgba(523B29ff) 45deg
    col.border_inactive = rgba(442920cc) rgba(C68773cc) 45deg
    col.border_locked_active = rgba(060606ff) rgba(080909ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(0F1010cc) 45deg
}
